name: VPS Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            export PATH=$PATH:/root/.bun/bin:/usr/local/bin
            cd /var/www/JNTU-REDESIGN
            git pull origin main
            bun install
            bun run build
            pm2 reload jntu-website || pm2 restart jntu-website
            pm2 save
